2022-09-12 22:42:51,120 (custom models) DEBUG  user 4shivayash registred successfully
2022-09-12 22:43:00,836 (custom models) DEBUG User is successfully logged in

2022-09-12 23:34:27,192 (auth models) DEBUG  User vinayak registred successfully
2022-09-12 23:34:48,767 (auth models) DEBUG User vinayak logged in successfully 

2022-09-13 22:42:44,821 (customised auth models) DEBUG  User shivaraj registered successfully
2022-09-13 22:44:54,315 (customised auth models) DEBUG User shivaraj logged in successfully

2022-09-14 23:59:32,576 (Class Based view with serialisation) DEBUG User chethana logged in successfully
2022-09-15 00:00:25,588 (Class Based view with serialisation) DEBUG User chethana logged in successfully

2022-09-15 17:01:07,204 (CRUD Operation for Note) INFO {'id': 3, 'title': 'paracetomal', 'description': 'description-3', 'user': 3}
2022-09-15 17:01:07,207 (CRUD Operation for Note) DEBUG {'message': 'Note created successfully'}
2022-09-15 17:02:13,397 (CRUD Operation for Note) INFO [OrderedDict([('id', 3), ('title', 'paracetomal'), ('description', 'description-3'), ('user', 3)])]
2022-09-15 17:02:13,398 (CRUD Operation for Note) DEBUG {'message': 'Note retrieved successfully'}
2022-09-15 17:02:49,973 (CRUD Operation for Note) INFO {'id': 3, 'title': 'para-cetomaol-updated', 'description': 'description-updated', 'user': 3}
2022-09-15 17:02:49,974 (CRUD Operation for Note) DEBUG {'message': 'Note updated successfully'}
2022-09-15 17:03:08,006 (CRUD Operation for Note) DEBUG {'message': 'Note deleted successfully'}

2022-09-20 23:48:25,958 (CRUD Operation for Note) INFO [OrderedDict([('id', 4), ('title', 'time table'), ('description', 'description-1'), ('user', 32)])]
2022-09-20 23:48:26,598 (CRUD Operation for Note) DEBUG {'message': 'Note retrieved successfully'}
2022-09-20 23:55:52,292 (CRUD Operation for Note) INFO {'id': 5, 'title': 'time table', 'description': 'description-1', 'user': 32}
2022-09-20 23:55:53,421 (CRUD Operation for Note) DEBUG {'message': 'Note created successfully'}
2022-09-20 23:58:45,258 (CRUD Operation for Note) INFO {'id': 4, 'title': '+time_table-updated', 'description': '+description-updated', 'user': 32}
2022-09-20 23:58:46,018 (CRUD Operation for Note) DEBUG {'message': 'Note updated successfully'}
2022-09-21 00:01:16,529 (CRUD Operation for Note) DEBUG {'message': 'Note deleted successfully'}
2022-09-22 17:18:18,262 (Class Based view with serialisation) ERROR {'username': [ErrorDetail(string='A user with that username already exists.', code='unique')]}
2022-09-22 17:18:18,265 django.request WARNING Bad Request: /user/register/
2022-09-22 17:19:23,152 django.request WARNING Not Found: /favicon.ico
2022-09-22 17:20:40,377 (CRUD Operation for Note With Authentication) INFO []
2022-09-22 17:20:40,381 (CRUD Operation for Note With Authentication) DEBUG {'message': 'Note retrieved successfully'}
2022-09-22 17:21:07,549 (CRUD Operation for Note With Authentication) INFO {'id': 7, 'title': 'time table', 'description': 'description-1', 'user': 35}
2022-09-22 17:21:08,631 (CRUD Operation for Note With Authentication) DEBUG {'message': 'Note created successfully'}
2022-09-22 17:21:52,392 (CRUD Operation for Note With Authentication) INFO [OrderedDict([('id', 7), ('title', 'time table'), ('description', 'description-1'), ('user', 35)])]
2022-09-22 17:21:53,563 (CRUD Operation for Note With Authentication) DEBUG {'message': 'Note retrieved successfully'}
2022-09-30 04:13:39,105 django.utils.autoreload INFO D:\CFP_Assignment\CFP_FundooNotes\users_app\middleware.py changed, reloading.
2022-09-30 04:19:25,506 django.utils.autoreload INFO D:\CFP_Assignment\CFP_FundooNotes\users_app\middleware.py changed, reloading.
2022-09-30 04:20:36,992 django.utils.autoreload INFO D:\CFP_Assignment\CFP_FundooNotes\users_app\middleware.py changed, reloading.
2022-09-30 04:20:51,159 django.request ERROR Internal Server Error: /user/login/
Traceback (most recent call last):
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\CFP_Assignment\CFP_FundooNotes\users_app\middleware.py", line 12, in __call__
    self.user_log(request)
  File "D:\CFP_Assignment\CFP_FundooNotes\users_app\middleware.py", line 17, in user_log
    user_data = UserLog.objects.filter(
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'method' into field. Choices are: created_at, id, request_method, request_url
2022-09-30 04:23:53,160 django.utils.autoreload INFO D:\CFP_Assignment\CFP_FundooNotes\users_app\middleware.py changed, reloading.
2022-09-30 04:24:19,703 django.utils.autoreload INFO D:\CFP_Assignment\CFP_FundooNotes\users_app\middleware.py changed, reloading.
2022-09-30 04:24:32,842 django.request ERROR Internal Server Error: /user/login/
Traceback (most recent call last):
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\CFP_Assignment\CFP_FundooNotes\users_app\middleware.py", line 12, in __call__
    self.user_log(request)
  File "D:\CFP_Assignment\CFP_FundooNotes\users_app\middleware.py", line 17, in user_log
    user_data = UserLog.objects.filter(
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\sql\query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\sql\query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\CFP_Assignment\CFP_FundooNotes\notes_env\lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'method' into field. Choices are: created_at, id, request_method, request_url
2022-09-30 04:25:20,223 django.utils.autoreload INFO D:\CFP_Assignment\CFP_FundooNotes\users_app\middleware.py changed, reloading.
2022-09-30 04:25:38,867 django.utils.autoreload INFO D:\CFP_Assignment\CFP_FundooNotes\users_app\middleware.py changed, reloading.
2022-09-30 04:26:14,135 django.utils.autoreload INFO D:\CFP_Assignment\CFP_FundooNotes\users_app\middleware.py changed, reloading.
2022-09-30 12:06:45,451 django.utils.autoreload INFO D:\CFP_Assignment\CFP_FundooNotes\users_app\middleware.py changed, reloading.
